# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skype',
            field=models.CharField(max_length=50, verbose_name='Skype'),
        ),
    ]
