# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.TextField()),
                ('user_last_name', models.TextField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.IntegerField(default=0)),
                ('user_skype', models.TextField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
