# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0002_auto_20160901_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
