# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_comments_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
