# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20160904_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
