# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_comments_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatars', verbose_name='Аватар'),
            preserve_default=False,
        ),
    ]
