# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_comments_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='avatar',
            field=models.ImageField(upload_to='', verbose_name='Аватар'),
        ),
    ]
